config/routes.rb
Thalys::Application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :posts

  get '/dashboard' => 'admin_pages#dashboard', as: 'dashboard'
  get '/settings' => 'admin_pages#settings', as: 'settings'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true
end

app/models/properties.rb
class Properties < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    @posts = Post.order("created_at DESC")
  end

  def settings
    if Properties.first
      @properties = Properties.first
    else
      @properties = Properties.new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    dashboard_path
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :created]

  def index
    @posts = Post.order("created_at DESC")
    #Properties.first ? @blogname = Properties.first.name : @blogname = ''
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = 'Post created.'
      redirect_to @post
    else
      flash[:alert] = 'Post not created, something went wrong.'
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = 'Post updated.'
      redirect_to @post
    else
      flash[:alert] = 'Post not updated: something went wrong.'
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.delete
      flash[:notice] = 'Post deleted.'
      redirect_to dashboard_path
    else
      flash[:alert] = 'Post not deleted. Something went wrong.'
      redirect_to dashboard_path
    end
  end
  
  private

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end
  
  def ipsum

  end
end

app/views/admin_pages/dashboard.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        = link_to 'Dashboard', dashboard_path
  %section.top-bar-section
    %ul.left
      %li.divider
      %li= link_to 'Create a new post', new_post_path
      / %li= link_to 'Blog settings', settings_path
      %li= link_to 'Request a new feature', 'http://asana.com'

.row
  .small-12.small-centered
    %table.table
      %thead
        %tr
          %th Title
          %th Content
          %th Edit
          %th Delete
      %tbody
        - @posts.each do |post|
          %tr{ id: post.id }
            %td 
              = post.title
            %td 
              = truncate(post.content)
            %td
              = link_to 'Edit', edit_post_path(post.id)
            %td
              = link_to 'Delete', post_path(post.id), method: :delete

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43693818-1', 'thequietestplace.com');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? yield(:title) : "The Quietest Place"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

  = render 'layouts/analytics'
%body
  / %nav.top-bar
  /   %ul.title-area
  /     %li.name
  /       %h1
  /         = link_to 'Starting North', nil

  = yield

  = javascript_include_tag "application"

app/views/posts/_comments.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'thequietestplace'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
    %noscript
  Please enable JavaScript to view the
  %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
%a.dsq-brlink{:href => "http://disqus.com"}
  comments powered by
  %span.logo-disqus Disqus

app/views/posts/_form.html.haml
= form_for post, class: 'post_form' do |f|
  = f.label 'Title'
  = f.text_field :title
  %br
  = f.label 'Content'
  = f.text_area :content
  = f.submit

app/views/posts/_post.html.haml
%br
%br

%h1
  = link_to post.title, post_path(post)
.post_date
  = post.created_at.to_s(:short_ordinal)
.post_content
  = markdown.render(post.content).html_safe

%br
%br
%br

app/views/posts/_post_links.html.haml
= link_to 'Share', '#', onclick: "window.open('https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}'+encodeURIComponent(location.href),'facebook-share-dialog','width=626,height=436'); return false;"

app/views/posts/edit.html.haml
.row
  .small-9.small-centered.columns
    %h1 Edit 
    = render 'form', post: @post

app/views/posts/index.html.haml
.heading
  .blogtitle
    The Quietest Place

.row
  .small-4.columns.small-offset-8.top-space-10
    %span.has-tip.tip-top{"data-tooltip" => "", title: "a scientist by day, a 'mother' after work, a partner by night - and everything that comes with it."} About The Quietest Place

.row
  .small-9.columns.small-centered
    = render @posts

  
.row#footer
  .small-6.columns.small-centered
    %h6.subheader
      written by 
      = link_to 'Carla', "mailto: carlasilvamatos@gmail.com"
      and built by 
      = link_to 'Job', "http://www.twitter.com/jobvo" 
      %br
      all rights reserved

app/views/posts/new.html.haml
.row
  .small-9.small-centered.columns
    %h1
      New post
    = render 'form', post: @post

.row
  .small-12.column.small-centered
    = link_to 'Markdown syntax', "http://daringfireball.net/projects/markdown/syntax"

app/views/posts/show.html.haml
.row
  .small-9.small-centered.columns
    = render @post